language: scala
jdk:
  - oraclejdk8
services:
  - mongodb
cache:
  directories:
    - $HOME/.ivy2/cache
env:
  - TEST_DIR=2.4/async/akka-examples
  - TEST_DIR=2.4/async/scalatra-atmosphere-embedded
  - TEST_DIR=2.4/async/scalatra-atmosphere-example
  - TEST_DIR=2.4/deployment/scalatra-heroku
  - JELASTIC_USERNAME="you@you.com" JELASTIC_PWD="iluvyou" TEST_DIR=2.4/deployment/scalatra-jelastic
  - TEST_DIR=2.4/formats/scalatra-commands
  - TEST_DIR=2.4/http/authentication-demo
  - TEST_DIR=2.4/http/scalatra-gzip
  - TEST_DIR=2.4/http/scalatra-http-client
  - TEST_DIR=2.4/http/scalatra-http-demo
  - TEST_DIR=2.4/http/scentry-auth-demo
  - TEST_DIR=2.4/persistence/riak-example
  - TEST_DIR=2.4/persistence/scalatra-casbah-example
  - TEST_DIR=2.4/persistence/scalatra-slick
  - TEST_DIR=2.4/persistence/scalatra-squeryl
  - TEST_DIR=2.4/resources/scalatra-coffeescript
  - TEST_DIR=2.4/resources/scalatra-less-css
  - TEST_DIR=2.4/swagger-example

script: cd $TEST_DIR && sbt test
